name: hMobCoins
version: '${version}'

main: com.hboj.hMobCoins.HMobCoins
api-version: '1.21'
load: POSTWORLD
softdepend: [PlaceholderAPI, PlayerPoints, Vault, MythicMobs, WorldGuard]
libraries:
  - org.xerial:sqlite-jdbc:3.46.1.0
  - com.mysql:mysql-connector-j:8.4.0

authors: [ hboj ]
website: https://hobojoe.dev/

commands:
  mobcoins:
    description: View player mob coins.
    usage: /mobcoins [player]
    permission: hmobcoins.mobcoins
